### ISSUE TITLE
Split ConDep into mode modules for easier customization?

### ISSUE THREAD

**Issue by thomaseyde** [condep/ConDep#26]
ConDep is very biased against the condep.exe-file and a certain deployment workflow which doesn't quite work in all circumstances. Well, not mine anyway ;-)

I don't expect the project to change course, nor do I want to build a deployment solution from scratch. But I would like to capitalize on the work done by the ConDep project and my time already invested in it.

From my point of view, the split ConDep does between the *.env.json and the target class is a bit odd:
- I am forced to put information in the json-file, which I would rather have in the target class.
- ConDep expects a json-file, it fails when there is none.
- I don't like to put passwords in the json-file, not in any source code for that matter.
- Because of small differences between internal test-servers, customers' test servers, and production servers, I need target classes like InternalTest, CustomerATest, CustomerAProd,
- Because I have added database-migrations to the mix, the user/password combo is even more complex.

I guess the simplest solution would be to make the json-file optional or have a `-noenv` parameter.

The harder solution would be to split ConDep.exe into one exe just doing setup, like deserialize the json and create the deployment runner class, then invoke the runner and pass the deserialized json and the deployment target name.

So if I want to create my own exe, all I have to do is to reference the deployment runner assembly, create the runner class and invoke it.

**Comment by torresdal** [comment]
Quite a few improvents around several of these concerns in 4.0. We will still have the config though.
