### ISSUE TITLE
Configuring a web.config per server in a load balance environment

### ISSUE THREAD

**Issue by JohnBloom** [condep/ConDep#27]
We have a system that is load balanced between two servers. At first we were deploying both servers identically. However, we have a recent requirement where we will need to configure a certain part of the web.config differently per server. 

At what point in the deployment process is this possible and is it possible to provide the unique information to the .json files since that is where the server definitions are?

**Comment by JohnBloom** [comment]
Here is a solution I am playing with but I am missing two key pieces of information:

In the ToEachServer function I want to update the connection string. Like this:
```
onLocalMachine.ToEachServer(server=>
{
   server.Configure.WebConfig("myConnectionString", "connection string info");
})
```

I have got the WebConfig extension method in place but I dont know what server I am working with. It would be nice at this point to have access to the .json node that represents this server. That way I could extend the server with per server configuration. Is that possible? Something like this:

```
{
     "Name": "myServer",
     "ConnectionString": "myConnectionString"
},
```
The other issue is that I dont know what the path to my web.config file is in the WebConfig extension. Is that possible to get as well?

**Comment by jjmartin** [comment]
could you start a counter before the ToEachServer and then call a method based on the iterated counter? 
(be careful about closures... )
http://stackoverflow.com/questions/5438307/detailed-explanation-of-variable-capture-in-closures

**Comment by torresdal** [comment]
John,

Could a custom operation (ForEachServerOperation) solve your problem?

```csharp
    public class WebConfigPerServerTransform : ForEachServerOperation
    {
        public override void Execute(ServerConfig server, IReportStatus status, ConDepSettings settings, CancellationToken token)
        {
            //server.Name
        }

        public override string Name
        {
            get { throw new System.NotImplementedException(); }
        }

        public override bool IsValid(Notification notification)
        {
            return true;
        }
    }
```

This operation will be executed once per server. As we speak I'm working on the docs for custom operations, so hopefully that will be available to you in a few hours.

I will also look into how the server object can be available in a Artifact, cause we've had this need from time to time too. Always found other ways (often better) to solve it though.

Generally speaking your new requirement sounds odd. I would not allow my load balanced servers to diff in any way.

**Comment by torresdal** [comment]
@jjmartin Your suggestion COULD work, but feels bad. Hopefully it can be solved with a custom operation.

**Comment by JohnBloom** [comment]
@torresdal believe me we are not excited about this either. We are integrating with a third party that will not let us be logged into their system from two different palaces so the load balanced severs end up stepping on each other. Our solution is to login with different users from each server. 

I understand that it is a slippery slope as the more divergent the servers get, the harder it is to give a consistent user experience.

I like your approach and as soon as we can get the server artifact I think I can put it into action.

**Comment by torresdal** [comment]
@JohnBloom The docs are now updated with a custom operation example using the `ForEachServerOperation`class: http://www.condep.io/docs/3-0/for-each-server-operation/

**Comment by jjmartin** [comment]
@torresdal  is there a way to just get customized data easily from the env.json files?   if there is already - could you add that documentation? That would also go some distance for achieving additional functionality.
meaning that if in the server area of the json file we could add additional fields (serverFriendlyName, customConnectionString) etc... and then pull them out of the serverConfig object

**Comment by torresdal** [comment]
@JohnBloom Not now there is. I'm not sure if it's a good idea. The env file was never intended to be a configuration file, but a infrastructure/inventory definition. I still think a custom operation is the best option for you. If you want to have your connection strings etc in a seperate config file, your're free to do so, and load it from your custom operation using plain c#.
